# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'login.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets

from common._util import start_bj, Home


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(300, 220)
        Form.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(0, 0, 300, 220))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap(start_bj))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setGeometry(QtCore.QRect(5, 20, 40, 40))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setGeometry(QtCore.QRect(5, 80, 40, 40))
        self.label_3.setObjectName("label_3")
        self.pushButton = QtWidgets.QPushButton(Form)
        self.pushButton.setGeometry(QtCore.QRect(80, 170, 150, 40))
        self.pushButton.setObjectName("pushButton")
        self.phone = QtWidgets.QTextEdit(Form)
        self.phone.setGeometry(QtCore.QRect(50,22, 240, 36))
        self.phone.setObjectName("phone")
        self.pasw = QtWidgets.QTextEdit(Form)
        self.pasw.setGeometry(QtCore.QRect(50, 82, 240, 36))
        self.pasw.setObjectName("pasw")
        self.alltuu = QtWidgets.QRadioButton(Form)
        self.alltuu.setGeometry(QtCore.QRect(60, 130, 100, 40))
        self.alltuu.setObjectName("alltuu")
        self.guituu = QtWidgets.QRadioButton(Form)
        self.guituu.setGeometry(QtCore.QRect(180, 130, 100, 40))
        self.guituu.setObjectName("guituu")
        self.label_4 = QtWidgets.QLabel(Form)
        self.label_4.setGeometry(QtCore.QRect(5, 130, 40, 40))
        self.label_4.setObjectName("label_4")
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(14)
        self.label_2.setFont(font)
        self.label_3.setFont(font)
        self.label_4.setFont(font)
        self.pushButton.setFont(font)
        self.alltuu.setFont(font)
        self.guituu.setFont(font)
        self.phone.setFont(font)
        self.pasw.setFont(font)
        self.label.raise_()
        self.label_2.raise_()
        self.label_3.raise_()
        self.pushButton.raise_()
        self.phone.raise_()
        self.pasw.raise_()
        self.guituu.raise_()
        self.alltuu.raise_()
        self.label_4.raise_()

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "登录页"))
        Form.setWindowIcon(QtGui.QIcon(Home))  # 设置icon
        self.label_2.setText(_translate("Form", "账户"))
        self.label_3.setText(_translate("Form", "密码"))
        self.pushButton.setText(_translate("Form", "登  陆"))
        self.alltuu.setText(_translate("Form", "线上环境"))
        self.guituu.setText(_translate("Form", "测试环境"))
        self.label_4.setText(_translate("Form", "环境"))
        self.phone.setPlaceholderText('手机号')
        self.pasw.setPlaceholderText('密码')
