# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'start_1.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(306, 228)
        Form.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.login = QtWidgets.QPushButton(Form)
        self.login.setGeometry(QtCore.QRect(30, 170, 91, 41))
        self.login.setObjectName("login")
        self.nologin = QtWidgets.QPushButton(Form)
        self.nologin.setGeometry(QtCore.QRect(180, 170, 91, 41))
        self.nologin.setObjectName("nologin")
        self.tips = QtWidgets.QLabel(Form)
        self.tips.setGeometry(QtCore.QRect(10, 20, 271, 61))
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(26)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.tips.setFont(font)
        self.tips.setStyleSheet("color: rgb(0, 0, 0);\n"
"font: 26pt \"楷体\";")
        self.tips.setObjectName("tips")
        self.logintxt = QtWidgets.QLabel(Form)
        self.logintxt.setGeometry(QtCore.QRect(40, 90, 241, 31))
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(12)
        self.logintxt.setFont(font)
        self.logintxt.setObjectName("logintxt")
        self.notxt = QtWidgets.QLabel(Form)
        self.notxt.setGeometry(QtCore.QRect(40, 120, 231, 31))
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(12)
        self.notxt.setFont(font)
        self.notxt.setObjectName("notxt")
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(0, 0, 1440, 1080))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("../img/bg.jpg"))
        self.label.setObjectName("label")
        self.label.raise_()
        self.login.raise_()
        self.nologin.raise_()
        self.tips.raise_()
        self.logintxt.raise_()
        self.notxt.raise_()

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.login.setText(_translate("Form", "登陆"))
        self.nologin.setText(_translate("Form", "不用登陆"))
        self.tips.setText(_translate("Form", "  接口测试工具"))
        self.logintxt.setText(_translate("Form", "登    陆：没token，需要获取；"))
        self.notxt.setText(_translate("Form", "不用登陆：有token，直接操作；"))
